name: mrms-cookbook-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyterlab
  - mystmd
  - nodejs=24.*
  - jupyterlab-myst
  - python=3.12
  - xarray
  - netcdf4
  - cartopy
  - numpy
  - s3fs
  - fsspec
  - cfgrib
  - requests
  - pandas
  - scipy
  - matplotlib
  - conda
  - ipykernel
  - ipywidgets
  - cftime
  - hvplot
  - holoviews
  - panel
  - metpy
  - cmweather
  - geoviews
  - jupyter_bokeh
